# Generated by Django 6.0.4 on 2026-04-21 14:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=5, unique=True)),
                ('league', models.CharField(choices=[('AL', 'American League'), ('NL', 'National League'), ('2LG', 'Both Leagues')], max_length=3)),
            ],
            options={
                'ordering': ['abbreviation'],
            },
        ),
        migrations.CreateModel(
            name='BattingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(50)])),
                ('war', models.FloatField()),
                ('games', models.IntegerField()),
                ('plate_appearances', models.IntegerField()),
                ('at_bats', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('doubles', models.IntegerField()),
                ('triples', models.IntegerField()),
                ('home_runs', models.IntegerField()),
                ('rbi', models.IntegerField()),
                ('stolen_bases', models.IntegerField()),
                ('caught_stealing', models.IntegerField()),
                ('walks', models.IntegerField()),
                ('strikeouts', models.IntegerField()),
                ('batting_avg', models.FloatField()),
                ('obp', models.FloatField()),
                ('slg', models.FloatField()),
                ('ops', models.FloatField()),
                ('ops_plus', models.IntegerField()),
                ('hbp', models.IntegerField()),
                ('source', models.CharField(choices=[('csv', 'CSV Import'), ('api', 'API Fetch')], default='csv', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_records', to='myapp.team')),
            ],
            options={
                'ordering': ['-ops'],
                'unique_together': {('player', 'team', 'age')},
            },
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp_max_f', models.FloatField(blank=True, null=True)),
                ('temp_min_f', models.FloatField(blank=True, null=True)),
                ('precipitation_in', models.FloatField(blank=True, null=True)),
                ('windspeed_max_mph', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('csv', 'CSV Import'), ('api', 'API Fetch')], default='api', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='myapp.city')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('city', 'date')},
            },
        ),
    ]
